lidar_topic: /hesai/pandar
imu_topic: /alphasense/imu
lidar_type: velodyne # livox velodyne ouster
min_radius: 0.7
max_radius: 150.0
point_filter_num: 2
time_scale: 0.001 # nclt: 0.001 other: 1000.0
enable_ahrs_initalization: false
enable_acc_correct: false

scan_resolution: 0.3
voxel_map_resolution: 0.3
max_iterations: 10

acc_cov: 0.1
gyr_cov: 0.1
ba_cov: 0.0001
bg_cov: 0.0001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
inti_pos_cov: 0.0001
init_vel_cov: 100.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001

# newer college
t_imu_lidar : [-0.001, -0.00855, 0.055]
R_imu_lidar : [1.11022302e-16, -1.00000000e+00,  0.00000000e+00,
              -1.00000000e+00,  1.11022302e-16, -0.00000000e+00,
              0.00000000e+00,  0.00000000e+00, -1.00000000e+00]