lidar_topic: /velodyne_points
imu_topic: /imu/data
lidar_type: velodyne # livox velodyne ouster
min_radius: 0.5
max_radius: 150.0
point_filter_num: 1
time_scale: 0.001 # nclt: 0.001 other: 1000.0
enable_ahrs_initalization: false
enable_acc_correct: false

scan_resolution: 0.3
voxel_map_resolution: 0.3
max_iterations: 10

acc_cov: 0.1
gyr_cov: 0.1
ba_cov: 0.0001
bg_cov: 0.0001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
inti_pos_cov: 0.0001
init_vel_cov: 100.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001

# newer college
t_imu_lidar : [0.08, 0.029, 0.03]
R_imu_lidar : [0.999945562, 0.009074807,  0.005149763,
               -0.009060897, 0.999955255, -0.002718066,
                -0.005174199, 0.002671256,  0.999983046]