localization:
  # Registration method
  registration_method: gicp

  # Compute ICP covariance and condition number
  compute_icp_covariance: true
  # 0: point to point 1: point to plane
  icp_covariance_method: 1

  icp_max_covariance: 0.01

  # Compute ICP observability 
  compute_icp_observability: false

  # Stop ICP if the transformation from the last iteration was this small.
  tf_epsilon: 0.00001

  # During ICP, two points won't be considered a correspondence if they are
  # at least this far from one another.
  corr_dist: 0.2

  # Iterate ICP this many times.
  iterations: 25 # Suggest 25 for NeBula Spot datasets

  # Maximum acceptable incremental rotation and translation.
  transform_thresholding: true
  max_translation: 1.0 # 0.05
  max_rotation: 1.0 # Radians - max 60 deg rotation

  # Number of threads GICP can use (3 threads ~ 3x speedup)
  # num_threads: 2 - defined in launch files to adapt to robot

  # Enable GICP timing output
  enable_timing_output: false
  
  # Radius for normal search
  normal_search_radius: 10

  # scan-to-map, scan has normals, map has normals as well, but the data comes
  # from scan sparse data therefore may be beneficial to recompute the covariance matrix
  recompute_covariance_local_map: false

# in general if there is no particular reason it should always be false,
# since it recomputes the covariances from scratch but we calculate them from normals
  recompute_covariance_scan: false
