ada_lio_dynamic:
    common:
        max_iteration: 3              # max iter of IEKF
        map_frame: "map"              # publish frame, e.g., previous LO/LIO methods used "camera_init", which is super inconvenient.
        lid_topic:  "/hesai/pandar"
        imu_topic:  "/alphasense/imu"

    preprocess:
        filter_size_map: 0.3         # voxel size
        point_filter_num: 2          # downsampling points, default values: 3 or 2 for LiVOX, 4 for Ouster and Velodyne
        lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
        scan_line: 32
        scan_rate: 10                # only need to be set for velodyne, unit: Hz,
        timestamp_unit: 3            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
        blind: 0.5

    adaptive:
        adaptive_voxelization_en: true # If true, Adaptive mode
        filter_size_map_smaller: 0.2   # It should be smaller than `filter_size_surf`
        neighbor_xy_thres: 5.0         # xy neighbor threshold
        num_thr_adaptive_voxelization: 800
        num_thr_adaptive_voxelization_neighbor: 500

    mapping:
        dynamic_remove: false
        cube_side_length: 1000.0     # note this must be larger than twice of the det_range
        det_range:     100.0         # LiDAR max range
        acc_cov: 0.1
        gyr_cov: 0.1
        b_acc_cov: 0.0001
        b_gyr_cov: 0.0001
        extrinsic_est_en:  false     # true: enable the online estimation of IMU-LiDAR extrinsic,
        extrinsic_T: [-0.001, -0.00855, 0.055]
        extrinsic_R: [1.11022302e-16, -1.00000000e+00,  0.00000000e+00,
                        -1.00000000e+00,  1.11022302e-16, -0.00000000e+00,
                        0.00000000e+00,  0.00000000e+00, -1.00000000e+00]

    publish:
        ikd_visualize_en: false
        path_en:  true
        scan_publish_en:  true       # false: close all the point cloud output
        dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
        scan_bodyframe_pub_en: false # true: output the point cloud scans in IMU-body-frame
