ada_lio_dynamic:
    common:
        max_iteration: 3              # max iter of IEKF
        map_frame: "map"              # publish frame, e.g., previous LO/LIO methods used "camera_init", which is super inconvenient.
        lid_topic:  "/velodyne_points"
        imu_topic:  "/imu/data"

    preprocess:
        filter_size_map: 0.3         # voxel size
        point_filter_num: 1          # downsampling points, default values: 3 or 2 for LiVOX, 4 for Ouster and Velodyne
        lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
        scan_line: 16
        scan_rate: 10                # only need to be set for velodyne, unit: Hz,
        timestamp_unit: 3            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
        blind: 0.5

    adaptive:
        adaptive_voxelization_en: true # If true, Adaptive mode
        filter_size_map_smaller: 0.2   # It should be smaller than `filter_size_surf`
        neighbor_xy_thres: 5.0         # xy neighbor threshold
        num_thr_adaptive_voxelization: 800
        num_thr_adaptive_voxelization_neighbor: 500

    mapping:
        dynamic_remove: false
        cube_side_length: 1000.0     # note this must be larger than twice of the det_range
        det_range:     100.0         # LiDAR max range
        acc_cov: 0.1
        gyr_cov: 0.1
        b_acc_cov: 0.0001
        b_gyr_cov: 0.0001
        extrinsic_est_en:  false     # true: enable the online estimation of IMU-LiDAR extrinsic,
        extrinsic_T: [0.08, 0.029, 0.03]
        extrinsic_R: [0.999212900, -0.000519121,  0.004000000,
               0.000516111,  0.999218492, -0.000939132,
               -0.004000000,  0.000802565,  0.999993652]

    publish:
        ikd_visualize_en: false
        path_en:  true
        scan_publish_en:  true       # false: close all the point cloud output
        dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
        scan_bodyframe_pub_en: false # true: output the point cloud scans in IMU-body-frame
